// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVnlBTqtoBqLYjE5SSi638DooYgBEgYqY',
    appId: '1:796833122032:web:4f0fb51c18f2140a342435',
    messagingSenderId: '796833122032',
    projectId: 'shut-up-app-3d55f',
    authDomain: 'shut-up-app-3d55f.firebaseapp.com',
    storageBucket: 'shut-up-app-3d55f.firebasestorage.app',
    measurementId: 'G-89EW2EYXFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWYOt-bofEFWmg68e4SHJayZQPXtzALv0',
    appId: '1:796833122032:android:ed21d7f1f5f1b3d2342435',
    messagingSenderId: '796833122032',
    projectId: 'shut-up-app-3d55f',
    storageBucket: 'shut-up-app-3d55f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN3QG9ZyA5FU5_6kCbSTa6qJGcui7DA3w',
    appId: '1:796833122032:ios:20f94fe19ad897ae342435',
    messagingSenderId: '796833122032',
    projectId: 'shut-up-app-3d55f',
    storageBucket: 'shut-up-app-3d55f.firebasestorage.app',
    androidClientId: '796833122032-l6b2eddfi6bj9kklkphljts2u203j219.apps.googleusercontent.com',
    iosClientId: '796833122032-eigk1o171lvif89kchvkubf88fuq6ccf.apps.googleusercontent.com',
    iosBundleId: 'com.example.shutUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN3QG9ZyA5FU5_6kCbSTa6qJGcui7DA3w',
    appId: '1:796833122032:ios:20f94fe19ad897ae342435',
    messagingSenderId: '796833122032',
    projectId: 'shut-up-app-3d55f',
    storageBucket: 'shut-up-app-3d55f.firebasestorage.app',
    androidClientId: '796833122032-l6b2eddfi6bj9kklkphljts2u203j219.apps.googleusercontent.com',
    iosClientId: '796833122032-eigk1o171lvif89kchvkubf88fuq6ccf.apps.googleusercontent.com',
    iosBundleId: 'com.example.shutUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVnlBTqtoBqLYjE5SSi638DooYgBEgYqY',
    appId: '1:796833122032:web:aea24669cd6a49e1342435',
    messagingSenderId: '796833122032',
    projectId: 'shut-up-app-3d55f',
    authDomain: 'shut-up-app-3d55f.firebaseapp.com',
    storageBucket: 'shut-up-app-3d55f.firebasestorage.app',
    measurementId: 'G-G7TXEZYDV5',
  );

}